[pcloud]
type = pcloud
hostname = api.pcloud.com

[pcloud_enc]
type = crypt
remote = pcloud:enc
filename_encryption = off
directory_name_encryption = false

[combine]
type = combine
upstreams = raw=pcloud:raw enc=pcloud_enc:

[pcloud_enc_private]
type = crypt
remote = R:raw/test/subdir_enc
filename_encryption = standard

